services:
  - type: web
    name: coride-web
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/coride-java-web-1.0.0.jar
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
