# Server Port
server.port=8080

# Spring Application Name
spring.application.name=coRide Java Web App

# H2 Database configuration with persistent file storage
spring.datasource.url=jdbc:h2:file:./data/coride_db;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# JPA & Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
